swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /account/accountId/transactions:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User transactions API
      description: API for fetching a user transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User transactions retrieved successully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /account/accountId/transactions/transactionId:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User transaction details API
      description: API for fetching a user transaction details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User transaction details retrieved successully
          schema:
            $ref: '#/definitions/TransactionDetails'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User transaction details API
      description: API for updating a transaction details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction details attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionDetailsSettings'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/TransactionDetailsSettingsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionDetails:
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          details:
            type: object
            properties:
              transaction-type:
                type: string
              category:
                type: string
              notes:
                type: string
  TransactionsResponse:
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          transactions:
            type: object
  TransactionDetailsSettings:
    properties:
      category:
        type: string
      notes:
        type: string
  TransactionDetailsSettingsResponse:
    properties:
      status:
        type: integer
      message: 
        type: string
